version: "3"
services:
  noted:
    image: "node:10.15.3-slim"
    command: "npm start"
    working_dir: /home/radek/dev/noted
    volumes:
      - ./:/home/radek/dev/noted
    ports:
      - "3000:3000"
    networks:
      - esnet
